DROP TABLE BOOKINGDETAILS;
DROP TABLE ROOMDETAILS;
DROP TABLE USERS;
DROP TABLE HOTELS;
DROP SEQUENCE USERS_SEQ;
DROP SEQUENCE HOTEL_SEQ;
DROP SEQUENCE BOOKINGDETAILS_SEQ;



CREATE TABLE USERS( USER_ID NUMBER(8), PASSWORD VARCHAR2(7) NOT NULL,ROLE VARCHAR2(10) NOT NULL,USER_NAME VARCHAR2(20) NOT NULL
    ,MOBILE_NO VARCHAR2(10) NOT NULL,PHONE VARCHAR2(10),ADDRESS VARCHAR2(50) NOT NULL, EMAIL VARCHAR2(30) NOT NULL,
    constraint  "USERS_PK" primary key ("USER_ID"));

CREATE SEQUENCE "USERS_SEQ" MAXVALUE 99999999 START WITH 1000;

ALTER TABLE USERS ADD CONSTRAINT "USERS_UK1" UNIQUE ("MOBILE_NO","EMAIL");



CREATE TABLE HOTELS(HOTEL_ID NUMBER(6) NOT NULL,CITY VARCHAR2(20) NOT NULL,HOTEL_NAME VARCHAR2(50) NOT NULL,ADDRESS VARCHAR2(50) NOT NULL,
    DESCRIPTION VARCHAR2(100) NOT NULL,AVG_RATE_PER_NIGHT NUMBER(7,2) NOT NULL,PHONE_NO1 VARCHAR2(10) NOT NULL,PHONE_NO2 VARCHAR2(10),RATING NUMBER(2,1) NOT NULL,
    EMAIL VARCHAR2(30) NOT NULL,FAX VARCHAR2(15),constraint  "HOTEL_PK" primary key ("HOTEL_ID"));

CREATE SEQUENCE "HOTEL_SEQ" MAXVALUE 999999 START WITH 100;

ALTER TABLE HOTELS ADD CONSTRAINT "HOTEL_UK1" UNIQUE ("PHONE_NO1","EMAIL");



CREATE TABLE ROOMDETAILS(HOTEL_ID NUMBER(6) NOT NULL,ROOM_ID VARCHAR2(4) NOT NULL,ROOM_NO VARCHAR2(3) NOT NULL,ROOM_TYPE VARCHAR2(20) NOT NULL,
    PER_NIGHT_RATE NUMBER(7,2) NOT NULL,AVAILABILITY VARCHAR2(1) NOT NULL,PHOTO BLOB,constraint ROOMDETAILS_PK primary key ("ROOM_ID"));

ALTER TABLE ROOMDETAILS ADD CONSTRAINT "ROOMDETAILS_FK" FOREIGN KEY ("HOTEL_ID") REFERENCES "HOTELS" ("HOTEL_ID");



CREATE table BOOKINGDETAILS(BOOKING_ID NUMBER(8),ROOM_ID VARCHAR2(4) NOT NULL,USER_ID NUMBER(8) NOT NULL,BOOKED_FROM DATE NOT NULL,BOOKED_TO DATE NOT NULL,
    NO_OF_ADULTS NUMBER(1) NOT NULL,NO_OF_CHILDREN NUMBER(1),AMOUNT NUMBER(8,2),constraint BOOKINGDETAILS_PK primary key ("BOOKING_ID"));

CREATE SEQUENCE "BOOKINGDETAILS_SEQ" MAXVALUE 99999999 START WITH 1 CYCLE;

ALTER TABLE BOOKINGDETAILS ADD CONSTRAINT "BOOKINGDETAILS_FK1" FOREIGN KEY ("USER_ID") REFERENCES USERS ("USER_ID");
ALTER TABLE BOOKINGDETAILS ADD CONSTRAINT "BOOKINGDETAILS_FK2" FOREIGN KEY ("ROOM_ID")REFERENCES ROOMDETAILS ("ROOM_ID");



INSERT INTO USERS VALUES(USERS_SEQ.NEXTVAL,'1a2b3c4','Admin','masteradmin','9999999999',null,'Airoli','masteradmin@cheapstays.com');

INSERT INTO HOTELS VALUES(HOTEL_SEQ.NEXTVAL,'Mumbai','Taj','109,Akashneem Marg,Near India Gate','Amazing budget stays.Very close to Gateway Of India.',0,'7894561230',null,4,'Taj_Mumbai@gmail.com',null);